import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";

import {AuthProvider} from "@/context/AuthContext";

// Components
import NavbarBootstrap from '@/components/NavbarBootstrap';
import {SearchProvider} from "@/context/SearchContext"
import Footer from '@/components/Footer';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <SearchProvider>
            <AuthProvider>
                <NavbarBootstrap/>
                {children}
                <Footer />
            </AuthProvider>
        </SearchProvider>
        </body>
        </html>
    );
}
